### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by herumes**
ShuttleAI now supports /v1/embeddings

Provider is now Direct OpenAI Enterprise, thus having the highest stability, and the fastest speeds (avg 0.5s) (So updated to High)

### CODE REVIEW

**Comment by zukixa** [comment]
tristan is this you

**Comment by herumes** [comment]
@zukixa sir, i am awaiting your review. all information is updated to be accurate, you may test for yourself if needed, or you may visit our status page for proven stability and reliability. put the energy drinks down for a min and update the list. :smile:

**Comment by herumes** [comment]
> tristan is this you

Sir it has been a whole day since you've replied to this pull request, but with no additional information or comments, or suggested changes even. I am curious as to why that is? Also I think its important to update the stability from "High" to "Meh" or "Low" for certain APIs as Shuttle is proven more stable than a lot of these, but all showing "High" isnt ideal either. An update is needed 😄  

If you have any concerns with this pull request, feel free to express such concerns 😃

**Comment by zukixa** [comment]
ur rly weird

**Pull request closed without merging**
