### PR TITLE
shard uwu

### PR DESCRIPTION
**Pull request by Puzzy124**

### CODE REVIEW

**Comment by zukixa** [comment]
unban me first 👎

**Comment by Puzzy124** [comment]
your unbanned sorry pooks

**Comment by zukixa** [comment]
additional rule; i don’t permit ddos skids

**Comment by Puzzy124** [comment]
Saying I ddos is equivalent to saying Tristan is the best programmer and has never touched a net. Your extremely dyslexic and must be off the autism scale if you think I ddos apis

**Pull request closed without merging**
